//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\eugene.krapivin@sap.com\source\repos\TranformerDSLParser\JsonTranslate.NET.Core.JustDsl\JustDsl.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Transformers.Core.JustDSL.Parser {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class JustDslLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, LPAREN=9, 
		RPAREN=10, FUNCTION_START=11, ARG_SEPERATOR=12, IDENTIFIER=13, STRING=14, 
		NUMBER=15, WS=16;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "LPAREN", 
		"RPAREN", "FUNCTION_START", "ARG_SEPERATOR", "IDENTIFIER", "STRING", "ESC", 
		"UNICODE", "HEX", "SAFECODEPOINT", "NUMBER", "INT", "EXP", "WS"
	};


	public JustDslLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public JustDslLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'{'", "'}'", "':'", "'['", "']'", "'true'", "'false'", "'null'", 
		"'('", "')'", "'#'", "','"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, "LPAREN", "RPAREN", 
		"FUNCTION_START", "ARG_SEPERATOR", "IDENTIFIER", "STRING", "NUMBER", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "JustDsl.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static JustDslLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x12', '\x97', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', 
		'\x3', '\xE', '\x3', '\xE', '\a', '\xE', 'T', '\n', '\xE', '\f', '\xE', 
		'\xE', '\xE', 'W', '\v', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\a', '\xF', '\\', '\n', '\xF', '\f', '\xF', '\xE', '\xF', '_', '\v', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x5', '\x10', '\x66', '\n', '\x10', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x5', '\x14', 
		's', '\n', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x6', 
		'\x14', 'x', '\n', '\x14', '\r', '\x14', '\xE', '\x14', 'y', '\x5', '\x14', 
		'|', '\n', '\x14', '\x3', '\x14', '\x5', '\x14', '\x7F', '\n', '\x14', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\a', '\x15', '\x84', '\n', 
		'\x15', '\f', '\x15', '\xE', '\x15', '\x87', '\v', '\x15', '\x5', '\x15', 
		'\x89', '\n', '\x15', '\x3', '\x16', '\x3', '\x16', '\x5', '\x16', '\x8D', 
		'\n', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x6', '\x17', 
		'\x92', '\n', '\x17', '\r', '\x17', '\xE', '\x17', '\x93', '\x3', '\x17', 
		'\x3', '\x17', '\x2', '\x2', '\x18', '\x3', '\x3', '\x5', '\x4', '\a', 
		'\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', 
		'\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', 
		'\x1D', '\x10', '\x1F', '\x2', '!', '\x2', '#', '\x2', '%', '\x2', '\'', 
		'\x11', ')', '\x2', '+', '\x2', '-', '\x12', '\x3', '\x2', '\f', '\x4', 
		'\x2', '\x43', '\\', '\x63', '|', '\x6', '\x2', '/', '/', '\x43', '\\', 
		'\x61', '\x61', '\x63', '|', '\n', '\x2', '$', '$', '\x31', '\x31', '^', 
		'^', '\x64', '\x64', 'h', 'h', 'p', 'p', 't', 't', 'v', 'v', '\x5', '\x2', 
		'\x32', ';', '\x43', 'H', '\x63', 'h', '\x5', '\x2', '\x2', '!', '$', 
		'$', '^', '^', '\x3', '\x2', '\x32', ';', '\x3', '\x2', '\x33', ';', '\x4', 
		'\x2', 'G', 'G', 'g', 'g', '\x4', '\x2', '-', '-', '/', '/', '\x5', '\x2', 
		'\v', '\f', '\xF', '\xF', '\"', '\"', '\x2', '\x9C', '\x2', '\x3', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\'', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', 
		'\x3', '/', '\x3', '\x2', '\x2', '\x2', '\x5', '\x31', '\x3', '\x2', '\x2', 
		'\x2', '\a', '\x33', '\x3', '\x2', '\x2', '\x2', '\t', '\x35', '\x3', 
		'\x2', '\x2', '\x2', '\v', '\x37', '\x3', '\x2', '\x2', '\x2', '\r', '\x39', 
		'\x3', '\x2', '\x2', '\x2', '\xF', '>', '\x3', '\x2', '\x2', '\x2', '\x11', 
		'\x44', '\x3', '\x2', '\x2', '\x2', '\x13', 'I', '\x3', '\x2', '\x2', 
		'\x2', '\x15', 'K', '\x3', '\x2', '\x2', '\x2', '\x17', 'M', '\x3', '\x2', 
		'\x2', '\x2', '\x19', 'O', '\x3', '\x2', '\x2', '\x2', '\x1B', 'Q', '\x3', 
		'\x2', '\x2', '\x2', '\x1D', 'X', '\x3', '\x2', '\x2', '\x2', '\x1F', 
		'\x62', '\x3', '\x2', '\x2', '\x2', '!', 'g', '\x3', '\x2', '\x2', '\x2', 
		'#', 'm', '\x3', '\x2', '\x2', '\x2', '%', 'o', '\x3', '\x2', '\x2', '\x2', 
		'\'', 'r', '\x3', '\x2', '\x2', '\x2', ')', '\x88', '\x3', '\x2', '\x2', 
		'\x2', '+', '\x8A', '\x3', '\x2', '\x2', '\x2', '-', '\x91', '\x3', '\x2', 
		'\x2', '\x2', '/', '\x30', '\a', '}', '\x2', '\x2', '\x30', '\x4', '\x3', 
		'\x2', '\x2', '\x2', '\x31', '\x32', '\a', '\x7F', '\x2', '\x2', '\x32', 
		'\x6', '\x3', '\x2', '\x2', '\x2', '\x33', '\x34', '\a', '<', '\x2', '\x2', 
		'\x34', '\b', '\x3', '\x2', '\x2', '\x2', '\x35', '\x36', '\a', ']', '\x2', 
		'\x2', '\x36', '\n', '\x3', '\x2', '\x2', '\x2', '\x37', '\x38', '\a', 
		'_', '\x2', '\x2', '\x38', '\f', '\x3', '\x2', '\x2', '\x2', '\x39', ':', 
		'\a', 'v', '\x2', '\x2', ':', ';', '\a', 't', '\x2', '\x2', ';', '<', 
		'\a', 'w', '\x2', '\x2', '<', '=', '\a', 'g', '\x2', '\x2', '=', '\xE', 
		'\x3', '\x2', '\x2', '\x2', '>', '?', '\a', 'h', '\x2', '\x2', '?', '@', 
		'\a', '\x63', '\x2', '\x2', '@', '\x41', '\a', 'n', '\x2', '\x2', '\x41', 
		'\x42', '\a', 'u', '\x2', '\x2', '\x42', '\x43', '\a', 'g', '\x2', '\x2', 
		'\x43', '\x10', '\x3', '\x2', '\x2', '\x2', '\x44', '\x45', '\a', 'p', 
		'\x2', '\x2', '\x45', '\x46', '\a', 'w', '\x2', '\x2', '\x46', 'G', '\a', 
		'n', '\x2', '\x2', 'G', 'H', '\a', 'n', '\x2', '\x2', 'H', '\x12', '\x3', 
		'\x2', '\x2', '\x2', 'I', 'J', '\a', '*', '\x2', '\x2', 'J', '\x14', '\x3', 
		'\x2', '\x2', '\x2', 'K', 'L', '\a', '+', '\x2', '\x2', 'L', '\x16', '\x3', 
		'\x2', '\x2', '\x2', 'M', 'N', '\a', '%', '\x2', '\x2', 'N', '\x18', '\x3', 
		'\x2', '\x2', '\x2', 'O', 'P', '\a', '.', '\x2', '\x2', 'P', '\x1A', '\x3', 
		'\x2', '\x2', '\x2', 'Q', 'U', '\t', '\x2', '\x2', '\x2', 'R', 'T', '\t', 
		'\x3', '\x2', '\x2', 'S', 'R', '\x3', '\x2', '\x2', '\x2', 'T', 'W', '\x3', 
		'\x2', '\x2', '\x2', 'U', 'S', '\x3', '\x2', '\x2', '\x2', 'U', 'V', '\x3', 
		'\x2', '\x2', '\x2', 'V', '\x1C', '\x3', '\x2', '\x2', '\x2', 'W', 'U', 
		'\x3', '\x2', '\x2', '\x2', 'X', ']', '\a', '$', '\x2', '\x2', 'Y', '\\', 
		'\x5', '\x1F', '\x10', '\x2', 'Z', '\\', '\x5', '%', '\x13', '\x2', '[', 
		'Y', '\x3', '\x2', '\x2', '\x2', '[', 'Z', '\x3', '\x2', '\x2', '\x2', 
		'\\', '_', '\x3', '\x2', '\x2', '\x2', ']', '[', '\x3', '\x2', '\x2', 
		'\x2', ']', '^', '\x3', '\x2', '\x2', '\x2', '^', '`', '\x3', '\x2', '\x2', 
		'\x2', '_', ']', '\x3', '\x2', '\x2', '\x2', '`', '\x61', '\a', '$', '\x2', 
		'\x2', '\x61', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x62', '\x65', '\a', 
		'^', '\x2', '\x2', '\x63', '\x66', '\t', '\x4', '\x2', '\x2', '\x64', 
		'\x66', '\x5', '!', '\x11', '\x2', '\x65', '\x63', '\x3', '\x2', '\x2', 
		'\x2', '\x65', '\x64', '\x3', '\x2', '\x2', '\x2', '\x66', ' ', '\x3', 
		'\x2', '\x2', '\x2', 'g', 'h', '\a', 'w', '\x2', '\x2', 'h', 'i', '\x5', 
		'#', '\x12', '\x2', 'i', 'j', '\x5', '#', '\x12', '\x2', 'j', 'k', '\x5', 
		'#', '\x12', '\x2', 'k', 'l', '\x5', '#', '\x12', '\x2', 'l', '\"', '\x3', 
		'\x2', '\x2', '\x2', 'm', 'n', '\t', '\x5', '\x2', '\x2', 'n', '$', '\x3', 
		'\x2', '\x2', '\x2', 'o', 'p', '\n', '\x6', '\x2', '\x2', 'p', '&', '\x3', 
		'\x2', '\x2', '\x2', 'q', 's', '\a', '/', '\x2', '\x2', 'r', 'q', '\x3', 
		'\x2', '\x2', '\x2', 'r', 's', '\x3', '\x2', '\x2', '\x2', 's', 't', '\x3', 
		'\x2', '\x2', '\x2', 't', '{', '\x5', ')', '\x15', '\x2', 'u', 'w', '\a', 
		'\x30', '\x2', '\x2', 'v', 'x', '\t', '\a', '\x2', '\x2', 'w', 'v', '\x3', 
		'\x2', '\x2', '\x2', 'x', 'y', '\x3', '\x2', '\x2', '\x2', 'y', 'w', '\x3', 
		'\x2', '\x2', '\x2', 'y', 'z', '\x3', '\x2', '\x2', '\x2', 'z', '|', '\x3', 
		'\x2', '\x2', '\x2', '{', 'u', '\x3', '\x2', '\x2', '\x2', '{', '|', '\x3', 
		'\x2', '\x2', '\x2', '|', '~', '\x3', '\x2', '\x2', '\x2', '}', '\x7F', 
		'\x5', '+', '\x16', '\x2', '~', '}', '\x3', '\x2', '\x2', '\x2', '~', 
		'\x7F', '\x3', '\x2', '\x2', '\x2', '\x7F', '(', '\x3', '\x2', '\x2', 
		'\x2', '\x80', '\x89', '\a', '\x32', '\x2', '\x2', '\x81', '\x85', '\t', 
		'\b', '\x2', '\x2', '\x82', '\x84', '\t', '\a', '\x2', '\x2', '\x83', 
		'\x82', '\x3', '\x2', '\x2', '\x2', '\x84', '\x87', '\x3', '\x2', '\x2', 
		'\x2', '\x85', '\x83', '\x3', '\x2', '\x2', '\x2', '\x85', '\x86', '\x3', 
		'\x2', '\x2', '\x2', '\x86', '\x89', '\x3', '\x2', '\x2', '\x2', '\x87', 
		'\x85', '\x3', '\x2', '\x2', '\x2', '\x88', '\x80', '\x3', '\x2', '\x2', 
		'\x2', '\x88', '\x81', '\x3', '\x2', '\x2', '\x2', '\x89', '*', '\x3', 
		'\x2', '\x2', '\x2', '\x8A', '\x8C', '\t', '\t', '\x2', '\x2', '\x8B', 
		'\x8D', '\t', '\n', '\x2', '\x2', '\x8C', '\x8B', '\x3', '\x2', '\x2', 
		'\x2', '\x8C', '\x8D', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x8E', '\x3', 
		'\x2', '\x2', '\x2', '\x8E', '\x8F', '\x5', ')', '\x15', '\x2', '\x8F', 
		',', '\x3', '\x2', '\x2', '\x2', '\x90', '\x92', '\t', '\v', '\x2', '\x2', 
		'\x91', '\x90', '\x3', '\x2', '\x2', '\x2', '\x92', '\x93', '\x3', '\x2', 
		'\x2', '\x2', '\x93', '\x91', '\x3', '\x2', '\x2', '\x2', '\x93', '\x94', 
		'\x3', '\x2', '\x2', '\x2', '\x94', '\x95', '\x3', '\x2', '\x2', '\x2', 
		'\x95', '\x96', '\b', '\x17', '\x2', '\x2', '\x96', '.', '\x3', '\x2', 
		'\x2', '\x2', '\xF', '\x2', 'U', '[', ']', '\x65', 'r', 'y', '{', '~', 
		'\x85', '\x88', '\x8C', '\x93', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Transformers.Core.JustDSL.Parser
